#
# WebComponents Snake Game
# Score Component Makefile
#

BUILDDIR=../../../build/components/score
FILES=score.html
SOURCES=score.ts
OUTFILE=score.js

all:
	tsc ${SOURCES} --outFile ${BUILDDIR}/${OUTFILE}
	cp ${FILES} ${BUILDDIR}/

clean:
	
