#
# WebComponents Snake Game
# Starfield Component Makefile
#

BUILDDIR=../../../build/components/starfield
FILES=starfield.html
SOURCES=starfield.ts
OUTFILE=starfield.js

all:
	tsc ${SOURCES} --outFile ${BUILDDIR}/${OUTFILE}
	cp ${FILES} ${BUILDDIR}/

clean:
	
