#
# WebComponents Snake Game
# Snake Component Makefile
#

BUILDDIR=../../../build/components/snake
FILES=snake.html
SOURCES=snake.ts game.ts
OUTFILE=snake.js

all:
	tsc ${SOURCES} --outFile ${BUILDDIR}/${OUTFILE}
	cp ${FILES} ${BUILDDIR}/

clean:
	
